definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        example: Kaindy
        type: string
      state:
        example: 1
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  service.CreateTagRequest:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - created_by
    - name
    type: object
  service.UpdateTagRequest:
    properties:
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - modified_by
    - state
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: support@swagger.io
    name: 联系人信息
    url: https://www.swagger.io/support 网址
  description: Go 语言编程之旅：一起用 Go 做项目 (描述信息)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/kaindy7633/go-programming-tour-book-blog-service
  title: 博客系统 (这里是标题)
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      consumes:
      - application/json
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
      tags:
      - 标签模块相关接口
    post:
      consumes:
      - application/json
      description: 创建一个薪的标签
      parameters:
      - description: 创建标签结构体
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/service.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 创建标签
      tags:
      - 标签模块相关接口
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除标签
      tags:
      - 标签模块相关接口
    get:
      description: 获取单个标签
      parameters:
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: 获取单个标签
      tags:
      - 标签模块相关接口
    put:
      consumes:
      - application/json
      parameters:
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新标签结构体
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/service.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Tag'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新标签
      tags:
      - 标签模块相关接口
swagger: "2.0"
